services:
  - type: web
    name: heart-attack-predictor
    env: python
    plan: free
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.11.9
    envVars:
      - key: FLASK_ENV
        value: production
